CREATE TABLE products (id BIGSERIAL PRIMARY KEY,
sku VARCHAR(255) NOT NULL UNIQUE,
name VARCHAR(255) NOT NULL,
description VARCHAR(255),
price DECIMAL(12, 2) NOT NULL CHECK (price >= 0), 
status VARCHAR(32) NOT NULL CHECK(status IN ('ACTIVE', 'INACTIVE'))
);