spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/logistics_platform
    username: commerce
    password: commerce

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
